spring:
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}
  ai:
    mcp:
      server:
        name: ${MCP_SERVER_NAME:math-calculator}
        version: ${MCP_SERVER_VERSION:1.0.0}
        type: ${MCP_SERVER_TYPE:SYNC}
        sse-message-endpoint: ${MCP_SSE_ENDPOINT:/mcp/message}
        annotation-scanner:
          enabled: ${MCP_ANNOTATION_SCANNER_ENABLED:false}

server:
  port: ${SERVER_PORT:44321}
